### ISSUE TITLE
WebRTC in android not working

### ISSUE THREAD

**Issue by equinox-cd** [jamalag/webrtc-Part-4#2]
Hello,
I was trying your tutorial in android settings mentioned in react-native-webrtc repo but its is not working can you please how us how to setup react-native-webrtc for android ?

**Comment by jamalag** [comment]
Hi, I somehow just stumbled upon your message here. Are you still facing the same problem?

**Comment by jamalag** [comment]
just in case, you might want to look at this thread ...
https://github.com/jamalag/webrtc-part-5-React-Hooks/issues/2

similar issue running on android

**Comment by sohel-khan** [comment]
Hi @jamalag  I am getting following error in mobile while connecting remotely ,

```
Possible Unhandled Promise Rejection (id: 10):
"Failed to set remote answer sdp: Called in wrong state: kHaveRemoteOffer"
```

Please help me to overcome this issue.. Thanks in advance
